### ISSUE TITLE
Error on building the project: taxonomy_list.html required

### ISSUE THREAD

**Issue by P1R** [cydave/zola-theme-papermod#2]
Hello, I was trying to build the project but I got into an issue that could not solve which is finding a required file called taxonomy_list.html. (My guess the file was excluded from the repository)
```sh
zola build
Building site...
Checking all internal links with anchors.
> Successfully checked 0 internal link(s) with anchors.
-> Creating 5 pages (0 orphan) and 3 sections
Error: Failed to build the site
Error: Failed to render a list of tags page.
Error: Reason: Tried to render `taxonomy_list.html` but the template wasn't found
```

**Comment by cydave** [comment]
Hey, could you provide me with your config.toml and maybe your repository?
I only implemented a bare minimum and may have forgotten to implement this as I never ran into this error.

**Comment by P1R** [comment]
Hello, Please notice that I was following your documentation and also copy sections from the config.toml example, after I was uncomenting is section to also understand the template and fixing the errors until I got into the one I could not solve.

here is the toml file data:

```toml
# The URL the site will be built for
base_url = "https://decentralizedscience.org"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = false

taxonomies = [
    { name = "tags", feed = true }
]

[markdown]
# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = true

# Papermod Theme
theme = "papermod"

[extra]
# Put all your custom variables here

[extra.papermod]
title = "PaperMod"
default_theme = "auto"
theme = "light"
language_direction = "auto"
keywords = ["keyword1", "keyword2", "keyword3"]
#show_theme_toggle = true
#show_scroll_to_top = true
#show_code_copy_buttons = true
#show_reading_time = true
#show_word_count = false
#show_post_nav_links = true
#show_post_meta = true
#default_toc_open = false
#edit_post_url = "https://github.com/cydave/zola-theme-papermod/tree/master"
##copyright = ""
date_format = "%Y-%m-%d"
#navigation = [
#    { url = "$BASE_URL/archive", title = "Archive" },
#    { url = "$BASE_URL/tags", title = "Tags" },
#    { url = "https://getzola.com/", title = "Zola", is_external = true }
#]

home_title = "PaperMod"
home_content = "Welcome to a demo of the PaperMod theme!<br><b>PaperMod</b> is a simple but fast and responsive theme with a useful feature-set that enhances UX.<br>Do give a 🌟 on Github !<br>PaperMod is based on the hugo-PaperMod theme."
social_icons = [
    { url = "https://github.com/cydave", title = "GitHub", icon = "github" },
    { url = "https://infosec.exchange/@cydave", title = "Mastodon", icon = "mastodon" },
    { url = "https://twitter.com/_cydave", title = "Twitter", icon = "twitter" },
    { url = "$BASE_URL/atom.xml", title = "RSS", icon = "rss" },
]
```

Best Regards.
